# docker-compose.yml
version: '3.8'

services:
  db:
    image: 'mysql:8.0'
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=xiaofeng
      - MYSQL_PASSWORD=f85859852
      - MYSQL_ROOT_PASSWORD=f85859852
    volumes:
      - './db_data:/var/lib/mysql'
    ports:
      - '3306:3306'
