import '../styles/globals.css'
import NavBar from '~/components/navbar'

export const metadata = {
  title: '个人博客',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="zh-CN">
      <body>
        {children}
      </body>
    </html>
  )
}
